services:
  app:
    build: .
    container_name: portal-academico-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
      - meilisearch
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: portal-academico-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: portal-academico-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: portal-academico-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  db_data:
  redis_data:
  meili_data:
